### ISSUE TITLE
Необходим перевод описания на русский

### ISSUE THREAD

**Issue by pbuk2** [vasvl123/OneScriptDB#25]
Если можно, сделайте перевод описания проекта на русском.

**Comment by vasvl123** [comment]
Спасибо за интерес к проекту!
Вот есть описание: https://uascript.net/help_ru
Правда уже немного устаревшее, много изменений делал в последнее время.

**Comment by vasvl123** [comment]
Здесь описание:
https://uascript.net/useyourmind
